### ISSUE TITLE
ID2.0.4: I want to be able to view patient history

### ISSUE THREAD

**Issue by MarcOlivierLajeunesse** [CMPUT401/vettr_server#14]

**Comment by MarcOlivierLajeunesse** [comment]
Front-end is almost done. Just need to format the date, and make the UI look nicer.

**Comment by MarcOlivierLajeunesse** [comment]
Front-end is now complete. just needs acceptance testing.

**Comment by justinbarclay** [comment]
Backend should be done

**Comment by MarcOlivierLajeunesse** [comment]
Testing covered by vaccine tests for now
