### ISSUE TITLE
ID2.0.5: I want to be able to view Medication list

### ISSUE THREAD

**Issue by MarcOlivierLajeunesse** [CMPUT401/vettr_server#15]

**Comment by MarcOlivierLajeunesse** [comment]
part of front end implemented. almost identical to medical history. needs back-end api.

**Comment by mack1070101** [comment]
It looks like @justinbarclay already did this one. Can you confirm?

**Comment by MarcOlivierLajeunesse** [comment]
Most of the front-end is complete. medications need to be filtered as to only display medicine, and not vaccines and others.

**Comment by MarcOlivierLajeunesse** [comment]
Front end complete. needs tests.

**Comment by MarcOlivierLajeunesse** [comment]
testing covered by vaccines for now
