### ISSUE TITLE
ID2.0.7: I want to be able to view Radiography history

### ISSUE THREAD

**Issue by MarcOlivierLajeunesse** [CMPUT401/vettr_server#17]

**Comment by MarcOlivierLajeunesse** [comment]
very similar to medical history. needs back-end api.

**Comment by mack1070101** [comment]
close because @MarcOlivierLajeunesse split into two issues

**Comment by MarcOlivierLajeunesse** [comment]
This is not a duplicate. view radiography and radiography history are separate issues.

**Comment by justinbarclay** [comment]
Back end should be done

**Comment by MarcOlivierLajeunesse** [comment]
Implementation wise, this is the same as viewing lab results. uses identical route. See https://github.com/CMPUT401/vettr_server/issues/44

**Comment by MarcOlivierLajeunesse** [comment]
front end complete. needs testing.

**Comment by MarcOlivierLajeunesse** [comment]
Testing covered by vaccines and upload/view radiography for now
