### ISSUE TITLE
Create Contact!

### ISSUE THREAD

**Issue by knewbury01** [CMPUT401/vettr_server#18]
need to be able to create a contact before we can view them duh!!!!!!!!!!

**Comment by justinbarclay** [comment]
Hey Kristy I think this was covered by Marco, in 1.0.1

**Comment by justinbarclay** [comment]
contact: {
      name: String,
      phoneNumber: String,
      faxNumber: String,
      email: String,
      address: String,
      type: String
    }
  }

**Comment by justinbarclay** [comment]
Back end should be done, pending any bugs found by Kristy
