### ISSUE TITLE
ID3.0.1: I want to be add a signature at the end

### ISSUE THREAD

**Issue by knewbury01** [CMPUT401/vettr_server#24]
this needs to be done before we can finalize issue 3.0.0
we will gather the image and store it locally for now
need to check before submitting form if sig is there or no

**Comment by knewbury01** [comment]
amendment: 
do not need to store the image locally. 

front end of this is complete, just need to decide how to store this on back end

**Comment by justinbarclay** [comment]
Back end complete, can this be marked done?
