### ISSUE TITLE
ID2.0.8:I want to be able to view patient vaccination history and add if necessary

### ISSUE THREAD

**Issue by mack1070101** [CMPUT401/vettr_server#31]
- Description/Details:
     As a vet I want to be able to view a patient's vaccination history through a scrollable list. The list contains things such as vaccine history- where in body, by who as well as date, time, as well as enter what type of antiparasitic is prescribed, as well as readministration date and reason for treatment.
Tests:
	- Try viewing the vaccination list of a patient without a vaccination history
	- Try viewing the vaccination list of a patient without an extensive vaccination history
	- Try adding a vaccination

**Comment by knewbury01** [comment]
need to do some date grappling. format format, so ugly atm
then determine what the new button on this is supposed to do,
then make it a bit prettier
then test
then should be done

**Comment by knewbury01** [comment]
test passes, need to figure out component testing moreso in polishing phase though.
