### ISSUE TITLE
ID2.0.9: I want to be able to log any communication with the client

### ISSUE THREAD

**Issue by mack1070101** [CMPUT401/vettr_server#32]
- Description/Details
      As a vet, I want to be able to select a client and track all communications I have with a client. After forums are finalized I can click add note and track the communications
Tests:
	- Try adding a communication log
	- Try adding a blank communication
	- Try finalizing a log
	- Try adding a note to a log

**Comment by justinbarclay** [comment]
Back end is done, using notes

**Comment by mack1070101** [comment]
@erichsueh Already covered by another user story
