### ISSUE TITLE
ID2.0.10 I want to be able to set alerts for a patient

### ISSUE THREAD

**Issue by mack1070101** [CMPUT401/vettr_server#33]
- Description/Details
      As a vet, I want to be able to add alerts to the patient file that communicate key or important information about a patient. This information might be something like "Patient needs to be muzzled" or "Patient has reactions to rabies vaccine"
Tests:
       - Try adding an alert
       - Try adding a blank alert
       - Try navigating away form alerts and navigating back

**Comment by mack1070101** [comment]
@erichsueh I think this one is done. Because we can set alerts in notes and medications. So I'm closing it out

**Comment by mack1070101** [comment]
reopen because I'm stupid and didn't think that the front end might not be done. But back end can support it

**Comment by justinbarclay** [comment]
Back end is done to set alerts regarding notes, vaccines, medicine, other
