### ISSUE TITLE
ID3.0.2: I want to have the medical history entry auto finalized at the end of the current day(?).

### ISSUE THREAD

**Issue by mack1070101** [CMPUT401/vettr_server#35]
- Description/Details:
     After two hours of opening the notes, I need the notes to auto finalize it so that no one is able to tamper with any of the information inside. The only thing that I'll be able to do is print the sheet. 
Tests:
	- Try editing the entry before it is finalized
	- Try editing the entry after it is finalized

**Comment by mack1070101** [comment]
Back end complete

**Comment by knewbury01** [comment]
only need to assure that route is protected from within (nonmanual) app transitions for editable med rec, but this will be two lines of code upon connecting hte pieces. can probably call this done.
