### ISSUE TITLE
ID1.0.1: I want to be able to add new client information

### ISSUE THREAD

**Issue by mack1070101** [CMPUT401/vettr_server#4]

**Comment by mack1070101** [comment]
Ability to create clients in back end has been completed, just need to deconflict any problems with Marco in the event they arise

**Comment by MarcOlivierLajeunesse** [comment]
Most of the front end functionality works. Can successfully post new clients. Still requires tests. Currently doesn't check for valid inputs, but only for necessary inputs.

**Comment by mack1070101** [comment]
Back end functionality is complete

**Comment by MarcOlivierLajeunesse** [comment]
Needs automated testing. Could later build a form validator for all forms. (make sure that phone numbers, emails, etc... are in the correct format.)
