### ISSUE TITLE
ID2.0.6a: I want to be able to add a lab result

### ISSUE THREAD

**Issue by MarcOlivierLajeunesse** [CMPUT401/vettr_server#42]

**Comment by MarcOlivierLajeunesse** [comment]
most of the front end is done

**Comment by MarcOlivierLajeunesse** [comment]
Front end is complete. should now be uploading image to server. needs testing.

**Comment by justinbarclay** [comment]
Back end is done

**Comment by MarcOlivierLajeunesse** [comment]
Acceptance tests complete. Made human read script that tests uploading and viewing lab results and radiography called Human_read_script_to_test_uploading_and_viewing_of_lab_results_and_radiographs.txt. In total, 28 checks, all pass.
