### ISSUE TITLE
ID2.0.7a: I want to be able to add radiography results.

### ISSUE THREAD

**Issue by MarcOlivierLajeunesse** [CMPUT401/vettr_server#45]

**Comment by justinbarclay** [comment]
Back end is done

**Comment by MarcOlivierLajeunesse** [comment]
Front-end done. needs testing.

**Comment by MarcOlivierLajeunesse** [comment]
Acceptance tests complete. Made human read script that tests uploading and viewing lab results and radiography called Human_read_script_to_test_uploading_and_viewing_of_lab_results_and_radiographs.txt. In total, 28 checks, all pass.
