### ISSUE TITLE
ID1.1.0: I want to be able to preview client information

### ISSUE THREAD

**Issue by MarcOlivierLajeunesse** [CMPUT401/vettr_server#6]

**Comment by MarcOlivierLajeunesse** [comment]
made a component to display the information. Now I need to find a way to pass the id from the clicked element to the component.

**Comment by mack1070101** [comment]
Back end portion is complete. Send get to /api/client, and it will respond with all clients (id, firstName, lastName)

**Comment by MarcOlivierLajeunesse** [comment]
Clicking on an item in the client list now redirect to /client-info/{id}, where it then retrieve's that patient's information. Currently working on displaying the information.

**Comment by MarcOlivierLajeunesse** [comment]
Now displaying client information. Still needs to fetch and display a summary of patient info

**Comment by MarcOlivierLajeunesse** [comment]
Displays info. Still needs a summary of pets' info, or at least a list of pet names with id's. Also needs acceptance tests.

**Comment by MarcOlivierLajeunesse** [comment]
Pet info/summary could be it's own userstory. Should get feedback from the client before making it.

**Comment by MarcOlivierLajeunesse** [comment]
Now displays pet names. Clicking on a pet name should redirect to the patient's page.

**Comment by MarcOlivierLajeunesse** [comment]
Acceptance testing is done.

**Comment by mack1070101** [comment]
This isn't working

**Comment by MarcOlivierLajeunesse** [comment]
Don't you mean view patient info isn't working?
