### ISSUE TITLE
ID 5.0.1 view contact info

### ISSUE THREAD

**Issue by knewbury01** [CMPUT401/vettr_server#8]
should separate into two tasks ( for front end):

1) be able to display contacts on contact search page, and then make contacts clickable?  (shouldnt have to search for them before transition to specific info? - but also will later be clickable from search bar, after 5.0.0 is done)

2) be able to display the info for that contact on a second page

**Comment by knewbury01** [comment]
task#2 complete and tested.

**Comment by justinbarclay** [comment]
Show client api should be created and tested

**Comment by justinbarclay** [comment]
Back end should be done pending any bugs

**Comment by knewbury01** [comment]
transition portion of front end task#1 is done... currently transitions on search bar submit but displaying contacts and adding interaction with them can be considered ID 5.0.0
